import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "MIRMEE",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-light ${roboto.className} max-w-[1440px] mx-auto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
