import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from "next/font/google"

export const metadata: Metadata = {
  title: "MIRMEE",
  description: "Generated by create next app",
};

const mont = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "400", "600", "800", "900"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-light ${mont.className} max-w-[1380px] mx-auto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
